// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getCodeExecution = `-- name: GetCodeExecution :one
SELECT id, job_id, tenant_id, stdout, stderr, compile_output, status, exec_time, memory, created_at FROM code_executions
WHERE job_id = $1 AND tenant_id = $2
`

type GetCodeExecutionParams struct {
	JobID    uuid.UUID `json:"job_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCodeExecution(ctx context.Context, arg GetCodeExecutionParams) (CodeExecution, error) {
	row := q.db.QueryRow(ctx, getCodeExecution, arg.JobID, arg.TenantID)
	var i CodeExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TenantID,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.Status,
		&i.ExecTime,
		&i.Memory,
		&i.CreatedAt,
	)
	return i, err
}

const getCodeProviderConfig = `-- name: GetCodeProviderConfig :one
SELECT id, tenant_id, provider, encrypted_config, created_at FROM code_provider_configs
WHERE tenant_id = $1 AND provider = $2
`

type GetCodeProviderConfigParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetCodeProviderConfig(ctx context.Context, arg GetCodeProviderConfigParams) (CodeProviderConfig, error) {
	row := q.db.QueryRow(ctx, getCodeProviderConfig, arg.TenantID, arg.Provider)
	var i CodeProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.EncryptedConfig,
		&i.CreatedAt,
	)
	return i, err
}

const insertCodeExecution = `-- name: InsertCodeExecution :one
INSERT INTO code_executions (job_id, tenant_id, stdout, stderr, compile_output, status, exec_time, memory)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, tenant_id, stdout, stderr, compile_output, status, exec_time, memory, created_at
`

type InsertCodeExecutionParams struct {
	JobID         uuid.UUID `json:"job_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	Stdout        string    `json:"stdout"`
	Stderr        string    `json:"stderr"`
	CompileOutput string    `json:"compile_output"`
	Status        string    `json:"status"`
	ExecTime      string    `json:"exec_time"`
	Memory        int32     `json:"memory"`
}

func (q *Queries) InsertCodeExecution(ctx context.Context, arg InsertCodeExecutionParams) (CodeExecution, error) {
	row := q.db.QueryRow(ctx, insertCodeExecution,
		arg.JobID,
		arg.TenantID,
		arg.Stdout,
		arg.Stderr,
		arg.CompileOutput,
		arg.Status,
		arg.ExecTime,
		arg.Memory,
	)
	var i CodeExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TenantID,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.Status,
		&i.ExecTime,
		&i.Memory,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCodeProviderConfig = `-- name: UpsertCodeProviderConfig :one
INSERT INTO code_provider_configs (tenant_id, provider, encrypted_config)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, provider) DO UPDATE
    SET encrypted_config = EXCLUDED.encrypted_config
RETURNING id, tenant_id, provider, encrypted_config, created_at
`

type UpsertCodeProviderConfigParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Provider        string    `json:"provider"`
	EncryptedConfig []byte    `json:"encrypted_config"`
}

func (q *Queries) UpsertCodeProviderConfig(ctx context.Context, arg UpsertCodeProviderConfigParams) (CodeProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertCodeProviderConfig, arg.TenantID, arg.Provider, arg.EncryptedConfig)
	var i CodeProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.EncryptedConfig,
		&i.CreatedAt,
	)
	return i, err
}
