// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_templates.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteEmailTemplate = `-- name: DeleteEmailTemplate :exec
DELETE FROM email_templates
WHERE tenant_id = $1 AND name = $2
`

type DeleteEmailTemplateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) DeleteEmailTemplate(ctx context.Context, arg DeleteEmailTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteEmailTemplate, arg.TenantID, arg.Name)
	return err
}

const getEmailTemplate = `-- name: GetEmailTemplate :one
SELECT id, tenant_id, name, subject, body, html, created_at, updated_at FROM email_templates
WHERE tenant_id = $1 AND name = $2
`

type GetEmailTemplateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) GetEmailTemplate(ctx context.Context, arg GetEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplate, arg.TenantID, arg.Name)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT id, tenant_id, name, subject, body, html, created_at, updated_at FROM email_templates
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListEmailTemplates(ctx context.Context, tenantID uuid.UUID) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailTemplate
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Subject,
			&i.Body,
			&i.Html,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmailTemplate = `-- name: UpsertEmailTemplate :one
INSERT INTO email_templates (tenant_id, name, subject, body, html)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, name) DO UPDATE
    SET subject    = EXCLUDED.subject,
        body       = EXCLUDED.body,
        html       = EXCLUDED.html,
        updated_at = NOW()
RETURNING id, tenant_id, name, subject, body, html, created_at, updated_at
`

type UpsertEmailTemplateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Subject  string    `json:"subject"`
	Body     string    `json:"body"`
	Html     string    `json:"html"`
}

func (q *Queries) UpsertEmailTemplate(ctx context.Context, arg UpsertEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, upsertEmailTemplate,
		arg.TenantID,
		arg.Name,
		arg.Subject,
		arg.Body,
		arg.Html,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Html,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
