// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getEmailProviderConfig = `-- name: GetEmailProviderConfig :one
SELECT id, tenant_id, provider, encrypted_config, created_at FROM email_provider_configs
WHERE tenant_id = $1 AND provider = $2
`

type GetEmailProviderConfigParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetEmailProviderConfig(ctx context.Context, arg GetEmailProviderConfigParams) (EmailProviderConfig, error) {
	row := q.db.QueryRow(ctx, getEmailProviderConfig, arg.TenantID, arg.Provider)
	var i EmailProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.EncryptedConfig,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmailProviderConfig = `-- name: UpsertEmailProviderConfig :one
INSERT INTO email_provider_configs (tenant_id, provider, encrypted_config)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, provider) DO UPDATE
    SET encrypted_config = EXCLUDED.encrypted_config
RETURNING id, tenant_id, provider, encrypted_config, created_at
`

type UpsertEmailProviderConfigParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Provider        string    `json:"provider"`
	EncryptedConfig []byte    `json:"encrypted_config"`
}

func (q *Queries) UpsertEmailProviderConfig(ctx context.Context, arg UpsertEmailProviderConfigParams) (EmailProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertEmailProviderConfig, arg.TenantID, arg.Provider, arg.EncryptedConfig)
	var i EmailProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.EncryptedConfig,
		&i.CreatedAt,
	)
	return i, err
}
