// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs SET
    status = 'running',
    started_at = NOW(),
    attempt = attempt + 1
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending' AND run_at <= NOW()
    ORDER BY run_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, job_type, payload, status, attempt, max_attempts, error, run_at, started_at, completed_at, created_at
`

func (q *Queries) ClaimNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.RunAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (tenant_id, job_type, payload)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, job_type, payload, status, attempt, max_attempts, error, run_at, started_at, completed_at, created_at
`

type CreateJobParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	JobType  string    `json:"job_type"`
	Payload  []byte    `json:"payload"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.TenantID, arg.JobType, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.RunAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, job_type, payload, status, attempt, max_attempts, error, run_at, started_at, completed_at, created_at FROM jobs
WHERE id = $1 AND tenant_id = $2
`

type GetJobParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.TenantID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.RunAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET
    status = $2,
    error = $3,
    completed_at = $4,
    run_at = $5
WHERE id = $1
RETURNING id, tenant_id, job_type, payload, status, attempt, max_attempts, error, run_at, started_at, completed_at, created_at
`

type UpdateJobStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	Error       pgtype.Text `json:"error"`
	CompletedAt *time.Time  `json:"completed_at"`
	RunAt       time.Time   `json:"run_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.CompletedAt,
		arg.RunAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.RunAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
