// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type OauthProviderConfig struct {
	ID                    uuid.UUID `json:"id"`
	TenantID              uuid.UUID `json:"tenant_id"`
	Provider              string    `json:"provider"`
	ClientID              string    `json:"client_id"`
	EncryptedClientSecret []byte    `json:"encrypted_client_secret"`
	CreatedAt             time.Time `json:"created_at"`
}

type OauthToken struct {
	ID                    uuid.UUID  `json:"id"`
	TenantID              uuid.UUID  `json:"tenant_id"`
	Provider              string     `json:"provider"`
	UserID                string     `json:"user_id"`
	EncryptedAccessToken  []byte     `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte     `json:"encrypted_refresh_token"`
	ExpiresAt             *time.Time `json:"expires_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Tenant struct {
	ID               uuid.UUID `json:"id"`
	ApiKeyHash       string    `json:"api_key_hash"`
	EncryptedDataKey []byte    `json:"encrypted_data_key"`
	CreatedAt        time.Time `json:"created_at"`
}
