// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE tenant_id = $1 AND provider = $2 AND user_id = $3
`

type DeleteOAuthTokenParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Provider string    `json:"provider"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthToken, arg.TenantID, arg.Provider, arg.UserID)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, tenant_id, provider, user_id, encrypted_access_token, encrypted_refresh_token, expires_at, created_at, updated_at FROM oauth_tokens
WHERE tenant_id = $1 AND provider = $2 AND user_id = $3
`

type GetOAuthTokenParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Provider string    `json:"provider"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, arg.TenantID, arg.Provider, arg.UserID)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.UserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT id, tenant_id, provider, client_id, encrypted_client_secret, created_at FROM oauth_provider_configs
WHERE tenant_id = $1 AND provider = $2
`

type GetProviderConfigParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (OauthProviderConfig, error) {
	row := q.db.QueryRow(ctx, getProviderConfig, arg.TenantID, arg.Provider)
	var i OauthProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :one
INSERT INTO oauth_tokens (tenant_id, provider, user_id, encrypted_access_token, encrypted_refresh_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, provider, user_id) DO UPDATE
    SET encrypted_access_token  = EXCLUDED.encrypted_access_token,
        encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
        expires_at              = EXCLUDED.expires_at,
        updated_at              = NOW()
RETURNING id, tenant_id, provider, user_id, encrypted_access_token, encrypted_refresh_token, expires_at, created_at, updated_at
`

type UpsertOAuthTokenParams struct {
	TenantID              uuid.UUID  `json:"tenant_id"`
	Provider              string     `json:"provider"`
	UserID                string     `json:"user_id"`
	EncryptedAccessToken  []byte     `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte     `json:"encrypted_refresh_token"`
	ExpiresAt             *time.Time `json:"expires_at"`
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, upsertOAuthToken,
		arg.TenantID,
		arg.Provider,
		arg.UserID,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.UserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderConfig = `-- name: UpsertProviderConfig :one
INSERT INTO oauth_provider_configs (tenant_id, provider, client_id, encrypted_client_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, provider) DO UPDATE
    SET client_id = EXCLUDED.client_id,
        encrypted_client_secret = EXCLUDED.encrypted_client_secret
RETURNING id, tenant_id, provider, client_id, encrypted_client_secret, created_at
`

type UpsertProviderConfigParams struct {
	TenantID              uuid.UUID `json:"tenant_id"`
	Provider              string    `json:"provider"`
	ClientID              string    `json:"client_id"`
	EncryptedClientSecret []byte    `json:"encrypted_client_secret"`
}

func (q *Queries) UpsertProviderConfig(ctx context.Context, arg UpsertProviderConfigParams) (OauthProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertProviderConfig,
		arg.TenantID,
		arg.Provider,
		arg.ClientID,
		arg.EncryptedClientSecret,
	)
	var i OauthProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ClientID,
		&i.EncryptedClientSecret,
		&i.CreatedAt,
	)
	return i, err
}
