// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error
	GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error)
	GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (OauthProviderConfig, error)
	GetTenantByAPIKeyHash(ctx context.Context, apiKeyHash string) (Tenant, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error)
	UpsertProviderConfig(ctx context.Context, arg UpsertProviderConfigParams) (OauthProviderConfig, error)
}

var _ Querier = (*Queries)(nil)
