// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (api_key_hash, encrypted_data_key)
VALUES ($1, $2)
RETURNING id, api_key_hash, encrypted_data_key, created_at
`

type CreateTenantParams struct {
	ApiKeyHash       string `json:"api_key_hash"`
	EncryptedDataKey []byte `json:"encrypted_data_key"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ApiKeyHash, arg.EncryptedDataKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.EncryptedDataKey,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByAPIKeyHash = `-- name: GetTenantByAPIKeyHash :one
SELECT id, api_key_hash, encrypted_data_key, created_at FROM tenants
WHERE api_key_hash = $1
`

func (q *Queries) GetTenantByAPIKeyHash(ctx context.Context, apiKeyHash string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKeyHash, apiKeyHash)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.EncryptedDataKey,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, api_key_hash, encrypted_data_key, created_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.EncryptedDataKey,
		&i.CreatedAt,
	)
	return i, err
}
